server:
  port: 8080
  servlet:
    context-path: /meetyou
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/MeetYouDB
    username: root
    password: root123456
  data:
    redis:
      host: localhost
      port: 6379
      password:
mybatis-plus:
  mapper-locations: classpath:com/cx/meetyoubackend/dao/xml/*.xml
  type-aliases-package: com.cx.meetyoubackend.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
logging:
  level:
    org:
      springframework:
        security: DEBUG
jwt:
  secret-key: 'yourSecretKey'
  expiration-time: 3600000
cors:
  allowed-origin: "http://localhost:8081"
  allowed-methods: "POST, GET, OPTIONS, DELETE"
  max-age: 3600
  allowed-headers: "Content-Type, Accept"

